# name: Deploy to GitHub Pages

# on:
#   # Trigger the workflow every time you push to the `main` branch
#   push:
#     branches: [main]
#   # Allows you to run this workflow manually from the Actions tab on GitHub.
#   workflow_dispatch:

#   # Allow this job to clone the repo and create a page deployment
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out your repository using git
#         uses: actions/checkout@v2

#       - name: Use Node.js 20
#         uses: actions/setup-node@v2
#         with:
#           node-version: "20"
#           cache: "npm"

#       # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
#       - name: Install dependencies
#         run: npm ci

#       # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
#       - name: Build Astro
#         run: npm run build --if-present

#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v1
#         with:
#           path: ./dist

#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v1

name: Deploy Astro to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Astro
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload to VPS via SCP
        run: |
          scp -r ./dist/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEST }}
